{{- if .Values.k8sExporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sigscalr.fullname" . }}-events-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sigscalr-events-exporter.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sigscalr-events-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sigscalr-events-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sigscalr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.k8sExporter.image.repository }}:{{ .Values.k8sExporter.image.tag }}"
          imagePullPolicy: {{ .Values.k8sExporter.image.pullPolicy }}
          args:
            - -conf=/data/config.yaml
          volumeMounts:
            - mountPath: /data
              name: cfg
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: cfg
          configMap:
            name: {{ .Chart.Name }}-k8s-events-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-k8s-events-config
  labels:
    {{- include "sigscalr-events-exporter.labels" . | nindent 4}}
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    logLevel: info
    throttlePeriod: 30
    logFormat: json
    route:
      routes:
        - match:
            - receiver: "sigscalr"
    receivers:
      - name: "sigscalr"
        elasticsearch:
          hosts:
            - http://{{ include "sigscalr.fullname" . }}:{{ .Values.sigscalr.configs.ingestPort }}/elastic
          index: {{ .Values.k8sExporter.configs.index }}
          useEventID: false
{{ end }}