apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: {{ include "sigscalr.fullname" . }}-ingest-server
    namespace: {{ .Release.Namespace }}
    labels:
        {{ include "sigscalr-ingest-server.labels" . | nindent 6 }}
spec:
  selector:
    matchLabels:
      {{ include "sigscalr-ingest-server.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "sigscalr.fullname" . }}-ingest-svc
  replicas: {{ .Values.sigscalr.ingestReplicas }}
  podManagementPolicy: "Parallel"
  template:
    metadata:
      {{ with .Values.podAnnotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      labels:
        {{ include "sigscalr-ingest-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- $licenseName := include "sigscalr-license.name" . -}}
      {{ with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      serviceAccountName: {{ include "sigscalr.serviceAccountName" . }}
      securityContext:
        {{ toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{ toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.sigscalr.image.repository }}:{{ .Values.sigscalr.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.sigscalr.image.pullPolicy }}
          command: ["./sigscalr", "--config", "server.yaml"]
          # startupProbe:
          #   httpGet:
          #     path: /api/health
          #     port: ingestport
          #     scheme: HTTP
          #   failureThreshold: 30
          #   periodSeconds: 1
          # livenessProbe:
          #   httpGet:
          #     path: /api/health
          #     port: ingestport
          #     scheme: HTTP
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          ports:
            - name: ingestport
              containerPort: {{ .Values.sigscalr.configs.ingestPort }}
              protocol: TCP
          volumeMounts:
          {{ if $licenseName }}
            - name: {{ .Chart.Name }}-license
              mountPath: /sigscalr/{{ $licenseName }}
              subPath: {{ $licenseName }}
          {{ end }}
            - name: {{ .Chart.Name }}-volume-claim
              mountPath: /sigscalr/data
            - name: {{ .Chart.Name }}-ingest-config
              mountPath: /sigscalr/server.yaml
              subPath: server.yaml
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
      terminationGracePeriodSeconds: 1800 # Purposely set to 30 minutes to avoid data loss on s3 flush
      volumes:
        - name: {{ .Chart.Name }}-ingest-config
          configMap:
            name: {{ .Chart.Name }}-ingest-config
            items:
            - key: server.yaml
              path: server.yaml
      {{ if $licenseName }}
        - name: {{ .Chart.Name }}-license
          configMap:
            name: {{ .Chart.Name }}-license
            items:
            - key: {{ $licenseName }}
              path: {{ $licenseName }}
      {{ end }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Chart.Name }}-volume-claim
      namespace: {{ .Release.Namespace }}
    spec:
      {{ include "sigscalr.storageClass" . | nindent 6 }}
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          {{ include "sigscalr-pvc.size" . | nindent 10 }}