apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-ingest-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "sigscalr.labels" . | nindent 4 }}
data:
  server.yaml: |-
    queryNode: false
    ingestNode: true
    dataDiskThresholdPercent: 10
    licenseKeyPath: {{ include "sigscalr-license.name" . }}
    {{ if .Values.logsExporter.enabled }}
    esVersion: "8.9.3"
    {{ else }}
    esVersion: "7.9.3"
    {{ end }}
    {{- toYaml .Values.sigscalr.configs | nindent 4 }}
    {{ if .Values.etcd.enabled }}
    etcd:
      enabled: true
      seedUrls:
        - http://{{ .Release.Name }}-etcd-headless:2380
    {{ end }}