apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: {{ include "sigscalr.fullname" . }}
    namespace: {{ .Release.Namespace }}
    labels:
        {{ include "sigscalr-server.labels" . | nindent 6 }}
spec:
  selector:
    matchLabels:
      {{ include "sigscalr-server.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "sigscalr.serviceAccountName" . }}
  replicas: 1
  template:
    metadata:
      {{ with .Values.podAnnotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      labels:
        {{ include "sigscalr-server.selectorLabels" . | nindent 8 }}
    spec:
      {{ with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      serviceAccountName: {{ include "sigscalr.serviceAccountName" . }}
      securityContext:
        {{ toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{ toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.sigscalr.image.repository }}:{{ .Values.sigscalr.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.sigscalr.image.pullPolicy }}
          command: ["./sigscalr", "--config", "server.yaml"]
          startupProbe:
            httpGet:
              path: /api/health
              port: queryport
              scheme: HTTP
            httpGet:
              path: /api/health
              port: ingestport
              scheme: HTTP
            failureThreshold: 30
            periodSeconds: 1
          livenessProbe:
            httpGet:
              path: /api/health
              port: queryport
              scheme: HTTP
            httpGet:
              path: /api/health
              port: ingestport
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
          ports:
            - name: queryport
              containerPort: {{ .Values.sigscalr.configs.queryPort }}
              protocol: TCP
            - name: ingestport
              containerPort: {{ .Values.sigscalr.configs.ingestPort }}
              protocol: TCP
          volumeMounts:
            - name: {{ .Chart.Name }}-volume-claim
              mountPath: /sigscalr/data
            - name: {{ .Chart.Name }}-server-config
              mountPath: /sigscalr/server.yaml
              subPath: server.yaml
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: {{ .Chart.Name }}-server-config
        configMap:
          name: {{ .Chart.Name }}-server-config
          items:
          - key: server.yaml
            path: server.yaml
  volumeClaimTemplates:
  - metadata:
      name: {{ .Chart.Name }}-volume-claim
      namespace: {{ .Release.Namespace }}
    spec:
      {{ include "sigscalr.storageClass" . | nindent 6 }}
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          {{ include "sigscalr-pvc.size" . | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sigscalr.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "sigscalr-server.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.sigscalr.configs.ingestPort }}
      targetPort: ingestport
      protocol: TCP
      name: ingestport
    - port: {{ .Values.sigscalr.configs.queryPort }}
      targetPort: queryport
      protocol: TCP
      name: queryport
  selector:
    {{ include "sigscalr-server.selectorLabels" . | nindent 4 }}