apiVersion: v1
kind: Service
metadata:
  name: {{ include "sigscalr.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sigscalr-server.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.sigscalr.core.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sigscalr-server.selectorLabels" . | nindent 4 }}