# Default values for sigscalr.
sigscalr:
  core:
    image:
      repository: 872191018532.dkr.ecr.us-east-1.amazonaws.com/sigscalr-dev
      pullPolicy: Always
      tag: latest
      # by default, a headless service is always created for sigscalr. Another service can be created using configs below
    service:
      alternateServiceType: ""
      port: 80
      annotations: {}


  ui:
    enabled: true
    image:
      repository: 872191018532.dkr.ecr.us-east-1.amazonaws.com/sigscalrui-dev
      pullPolicy: Always
      tag: latest
    service: 
      serviceType: LoadBalancer
      port: 5000
      annotations: {}
  
  configs:
    port: 8081 # port used for sigscalr server
    uiPort: 8000 # port used for sigscalr ui webserver

  storage:
    # set to true for default class, else will create a new class with below arguments
    defaultClass: true 

    # Use EBS volume as default storage class
    # awsEBS:
    #   parameters: {}

    # Create volume on a single node. The path must be present on the host 
    # local:
    #   hostname: minikube
    #   capacity: 5Gi 
    #   path: /data

k8sExporter:
  # Enable k8s events exporter to automatically ship events to sigscalr. If enabled, a cluster role will be created
  enabled: true
  image:
    repository: ghcr.io/opsgenie/kubernetes-event-exporter
    pullPolicy: IfNotPresent
    tag: v0.11
  configs:
    index: kubernetes-events # output index name for kubernetes events

logsExporter:
  # Logs Exporter launches a fluentd daemonset that tails all container logs at /var/log/containers/*.log
  enabled: true
  image:
    repository: fluent/fluentd-kubernetes-daemonset
    pullPolicy: IfNotPresent
    tag: v1.14-debian-elasticsearch7-1
  configs:
    # if indexPrefix is not defined, prefix defaults go to namespace-logs
    # all logs will go to indexPrefix-${record['kubernetes']['namespace_name']}
    indexPrefix: namespace

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  runAsUser: 1000


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}