# Default values for sigscalr.
sigscalr:
  image:
    repository: sigscalr
    pullPolicy: Always
    tag: 1.1.18
  ingest:
    service:
      serviceType: "ClusterIP"
      port: 8081
      annotations: {}
  query:
    service:
      serviceType: "ClusterIP"
      port: 8000
      annotations: {}
  licenseEnabled : false # todo: make this less hacky
  
  ingestReplicas: 3
  queryReplicas: 3
  # sigscalr configuration
  configs:
    ingestPort: 8081 # port used for sigscalr ingestion servers
    queryPort: 8000 # port used for sigscalr ui webserver
    # license:  "" # license file name
    # s3:
    #   enabled: false # if etcd is enabled, s3 is required
    #   bucketName: ""
    #   regionName: ""

  storage:
    # set to true for default class, else will create a new class with below arguments
    defaultClass: true

    # size of the volume the PVC will request
    size: 40Gi 

    # Use EBS volume as default storage class
    # awsEBS:
    #   parameters: {}

    # Create volume on a single node. The path must be present on the host 
    # local:
    #   hostname: minikube
    #   capacity: 5Gi 
    #   path: /data

# ETCD is used as a distributed key-value store for sigscalr horizontal scaling and HA
etcd:
  enabled: true
  auth:
    rbac:
      create: false  

k8sExporter:
  # Enable k8s events exporter to automatically ship events to sigscalr. If enabled, a cluster role will be created
  enabled: true
  image:
    repository: ghcr.io/opsgenie/kubernetes-event-exporter
    pullPolicy: IfNotPresent
    tag: v0.11
  configs:
    index: kubernetes-events # output index name for kubernetes events
  resources: {}
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi
logsExporter:
  # Logs Exporter launches a fluentd daemonset that tails all container logs at /var/log/containers/*.log
  enabled: true
  image:
    repository: fluent/fluentd-kubernetes-daemonset
    pullPolicy: IfNotPresent
    tag: v1.14-debian-elasticsearch7-1
  resources: {}
  #   limits:
  #     cpu: 500m
  #     memory: 512Mi
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  runAsUser: 1000


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}